name: mbvn_flutter_base
description: Company-wide Flutter base package for design system, network, widgets, error handling, utilities, and app configuration.
publish_to: 'none'
version: 0.1.0

environment:
  #sdk: ^3.6.0
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  intl: ^0.19.0
  matcher: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
